version: '3'

services:
  gpt-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpt-mcp-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - n8n-mcp-net
    restart: unless-stopped 

networks:
  n8n-mcp-net:
    external: true 